--==========================================================
-- SQL PRACTICE QUESTIONS
-- RETAIL SALES TABLE
--==========================================================


--==========================================================
-- 1. COUNTRY-WISE SALES PERFORMANCE
--==========================================================

-- Requirement:
-- Find total sales generated by each country.
-- Display country and total sales.
-- Sort from highest-selling country
-- to lowest-selling country.


SELECT country,
       SUM(sales_amount) AS total_sales
FROM retail_sales
GROUP BY country
ORDER BY total_sales DESC;


-- TRICK:
-- Country-wise  → GROUP BY country
-- Total sales   → SUM(sales_amount)
-- Highest first → ORDER BY DESC


--==========================================================
-- 2. CATEGORY-WISE REVENUE
--==========================================================

-- Requirement:
-- Find total sales for each product category.
-- Display only categories having sales
-- greater than 100,000.


SELECT category,
       SUM(sales_amount) AS total_sales
FROM retail_sales
GROUP BY category
HAVING SUM(sales_amount) > 100000;


-- TRICK:
-- SUM() result filtering → HAVING
--
-- WHERE  → Before GROUP BY
-- HAVING → After GROUP BY


--==========================================================
-- 3. COUNTRY-WISE NUMBER OF TRANSACTIONS
--==========================================================

-- Requirement:
-- Find the total number of sales transactions
-- for every country.
-- Display only countries having more than
-- 40 transactions.


SELECT country,
       COUNT(*) AS total_transactions
FROM retail_sales
GROUP BY country
HAVING COUNT(*) > 40;


-- NOTE:
-- With the current retail_sales table,
-- no country has more than 40 transactions.
--
-- So this query will return no rows.


-- TRICK:
-- Number of transactions → COUNT(*)
-- Country-wise            → GROUP BY country
-- More than 40            → HAVING COUNT(*) > 40


--==========================================================
-- 4. CATEGORY-WISE AVERAGE ORDER VALUE
--==========================================================

-- Requirement:
-- Calculate the average order value
-- for each product category.


SELECT category,
       AVG(sales_amount) AS average_order_value
FROM retail_sales
GROUP BY category;


-- TRICK:
-- Average   → AVG()
-- Category  → GROUP BY category


--==========================================================
-- 5. QUICK REVISION
--==========================================================


SUM()
    → Total sales / revenue

COUNT()
    → Number of transactions

AVG()
    → Average order value

GROUP BY
    → Country-wise / Category-wise result

HAVING
    → Filter grouped/aggregate results

ORDER BY DESC
    → Highest to lowest


--==========================================================
-- EASY FORMULAS
--==========================================================


-- Total Sales:

SELECT country,
       SUM(sales_amount) AS total_sales
FROM retail_sales
GROUP BY country
ORDER BY total_sales DESC;


-- Category Revenue > 100000:

SELECT category,
       SUM(sales_amount) AS total_sales
FROM retail_sales
GROUP BY category
HAVING SUM(sales_amount) > 100000;


-- Transactions > 40:

SELECT country,
       COUNT(*) AS total_transactions
FROM retail_sales
GROUP BY country
HAVING COUNT(*) > 40;


-- Average Order Value:

SELECT category,
       AVG(sales_amount) AS average_order_value
FROM retail_sales
GROUP BY category;


--==========================================================
-- MAIN TRICK TO REMEMBER
--==========================================================

Country-wise
    → GROUP BY country

Category-wise
    → GROUP BY category

Total
    → SUM()

Count
    → COUNT()

Average
    → AVG()

Filter normal rows
    → WHERE

Filter SUM / COUNT / AVG results
    → HAVING

Highest → Lowest
    → ORDER BY ... DESC